# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TPR_coms_Rcpp <- function(triangles, com) {
    .Call('_clustAnalytics_TPR_coms_Rcpp', PACKAGE = 'clustAnalytics', triangles, com)
}

triangle_participation_ratio_Rcpp <- function(EdgeList) {
    .Call('_clustAnalytics_triangle_participation_ratio_Rcpp', PACKAGE = 'clustAnalytics', EdgeList)
}

walk_step <- function(M, min_row) {
    .Call('_clustAnalytics_walk_step', PACKAGE = 'clustAnalytics', M, min_row)
}

walk_k_steps <- function(M, min_row, k) {
    invisible(.Call('_clustAnalytics_walk_k_steps', PACKAGE = 'clustAnalytics', M, min_row, k))
}

sample_fraction_H_i <- function(M, i, error = 0.1) {
    .Call('_clustAnalytics_sample_fraction_H_i', PACKAGE = 'clustAnalytics', M, i, error)
}

c_rs_table <- function(c1, c2) {
    .Call('_clustAnalytics_c_rs_table', PACKAGE = 'clustAnalytics', c1, c2)
}

count_contingency_tables <- function(c1, c2, error = 0.1) {
    .Call('_clustAnalytics_count_contingency_tables', PACKAGE = 'clustAnalytics', c1, c2, error)
}

count_labels <- function(c) {
    .Call('_clustAnalytics_count_labels', PACKAGE = 'clustAnalytics', c)
}

mutual_information_Cpp <- function(c1, c2, a, b) {
    .Call('_clustAnalytics_mutual_information_Cpp', PACKAGE = 'clustAnalytics', c1, c2, a, b)
}

vector_c_rs <- function(c1, c2) {
    .Call('_clustAnalytics_vector_c_rs', PACKAGE = 'clustAnalytics', c1, c2)
}

rcpp_hello_world <- function() {
    .Call('_clustAnalytics_rcpp_hello_world', PACKAGE = 'clustAnalytics')
}

randomize <- function(EdgeList, Q, weight_sel = "const_var", lower_bound = 0, upper_bound = -1) {
    .Call('_clustAnalytics_randomize', PACKAGE = 'clustAnalytics', EdgeList, Q, weight_sel, lower_bound, upper_bound)
}

cluster_auxiliary_values_Rcpp <- function(EdgeList, memb) {
    .Call('_clustAnalytics_cluster_auxiliary_values_Rcpp', PACKAGE = 'clustAnalytics', EdgeList, memb)
}

density_ratio_Rcpp <- function(aux_vals) {
    .Call('_clustAnalytics_density_ratio_Rcpp', PACKAGE = 'clustAnalytics', aux_vals)
}

local_density_ratio_Rcpp <- function(aux_vals) {
    .Call('_clustAnalytics_local_density_ratio_Rcpp', PACKAGE = 'clustAnalytics', aux_vals)
}

FOMD_Rcpp <- function(EdgeList, memb) {
    .Call('_clustAnalytics_FOMD_Rcpp', PACKAGE = 'clustAnalytics', EdgeList, memb)
}

out_degree_fractions_Rcpp <- function(EdgeList, memb) {
    .Call('_clustAnalytics_out_degree_fractions_Rcpp', PACKAGE = 'clustAnalytics', EdgeList, memb)
}

clustering_coefficient_Rcpp <- function(EdgeList, lower_bound = 0, upper_bound = 1) {
    .Call('_clustAnalytics_clustering_coefficient_Rcpp', PACKAGE = 'clustAnalytics', EdgeList, lower_bound, upper_bound)
}

transitivity_Rcpp <- function(EdgeList, lower_bound = 0, upper_bound = 1) {
    .Call('_clustAnalytics_transitivity_Rcpp', PACKAGE = 'clustAnalytics', EdgeList, lower_bound, upper_bound)
}

